# workflow to update app within the ENV #

name: update-app
on:
  push:
    branches: [ main ]
    paths:
    - .github/inputs/*
jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install or Update EaaS
        uses: jrzeszutek/install-or-update-action@v1.2.1
        with:
          environment-name: $EAAS_DEPLOYMENT_ID
          blueprint-id: $EAAS_BLUEPRINT_ID
          delete-old-blueprint: false
          inputs-file: ".github/inputs/inputs.yaml"
          
env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_TENANT: ${{ secrets.CLOUDIFY_TENANT }}
  EAAS_BLUEPRINT_ID: ${{ secrets.EAAS_BLUEPRINT_ID }}
  EAAS_DEPLOYMENT_ID: ${{ secrets.EAAS_DEPLOYMENT_ID }}
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  
  #CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  #CLOUDIFY_SSL_TRUST_ALL: ${{ secrets.CLOUDIFY_SSL_TRUST_ALL }}
